#!/usr/bin/env bash

COMPRESSION=compression
IGZIP=$COMPRESSION/isa-l-master
#ZLIB=$COMPRESSION/zlib-inflate
ZLIB=$COMPRESSION/otc_zlib
#ZLIB=$COMPRESSION/zlib-1.2.8
PAIRHMM=pairhmm

cd ftz
make
cd -

cd pairhmm
make
cd -

cd compression
./build
cd -

os=$(uname)
if [[ $os == "Linux" ]]; then

#g++ -z noexecstack -shared -fPIC -O3 -static-libgcc -static-libstdc++ \
#    $COMPRESSION/IntelDeflater.o $IGZIP/igzip/libigzip0c.a $ZLIB/libz.a \
#    $PAIRHMM/IntelPairHmm.o \
#    -o libIntelGKL.so

g++ -z noexecstack -shared -fPIC -O3 -static-libgcc -static-libstdc++ \
    $COMPRESSION/IntelDeflater.o $COMPRESSION/IntelInflater.o $IGZIP/lib/libisal.a $ZLIB/libz.a \
    $PAIRHMM/IntelPairHmm.o \
    ftz/ftz.o \
    -o libIntelGKL.so



elif [[ $os == "Darwin" ]]; then

g++ -shared -fPIC -O3 \
    $COMPRESSION/IntelDeflater.o $COMPRESSION/IntelInflater.o $IGZIP/lib/libisal.a $ZLIB/libz.a \
    $PAIRHMM/IntelPairHmm.o \
    ftz/ftz.o \
    -o libIntelGKL.dylib



else

echo "OS not supported" 1>&2

fi
