/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_gkl_ftz_FTZ */

#ifndef _Included_com_intel_gkl_ftz_FTZ
#define _Included_com_intel_gkl_ftz_FTZ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_gkl_ftz_FTZ
 * Method:    getFlushToZeroNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_gkl_ftz_FTZ_getFlushToZeroNative
  (JNIEnv *, jobject);

/*
 * Class:     com_intel_gkl_ftz_FTZ
 * Method:    setFlushToZeroNative
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_intel_gkl_ftz_FTZ_setFlushToZeroNative
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
