#!/usr/bin/env bash
IGZIP=isa-l-master
ZLIB=otc_zlib
#ZLIB=zlib-1.2.8

# build igzip library
cd $IGZIP
make clean
./autogen.sh
./configure CFLAGS="-fPIC" --prefix=$IGZIP/usr --libdir=$IGZIP/lib
make
make install
cd -

# build otc_zlib
cd $ZLIB
make clean
CFLAGS="-O3 -fPIC" ./configure --static
make

cd -

# build GKL shared library
javah -o IntelDeflater.h -cp ../../java com.intel.gkl.compression.IntelDeflater

g++ -c -fPIC -O3 -I$IGZIP/igzip/c_code/ -I$IGZIP/include \
    -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -I$JAVA_HOME/include/Darwin \
    IntelDeflater.cc
