#!/usr/bin/env bash
IGZIP=igzip_042
ZLIB=otc_zlib

# build igzip library
cd $IGZIP/igzip
make
cd -

# build otc_zlib
cd $ZLIB
make clean
CFLAGS="-fPIC" ./configure --static
make static
cd -

# build GKL shared library
javah -o IntelDeflater.h -cp ../../java com.intel.gkl.compression.IntelDeflater

g++ -c -fPIC -O3 -I$IGZIP/igzip/c_code/ -I$IGZIP/include \
    -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -I$JAVA_HOME/include/Darwin \
    IntelDeflater.cc
